## Standard Libraries
math - for math

urllib - for url Libraries

datetime - for dates and times

pickle & cPickle - for seralizing and deserializing data structures to save variables

os - os dependant functions


## Third party packages
numpy - scientific computing

scipy - core packages

pandas - table like data structures from DataFrame objects

matplotlib - plotting library

BeautifulSoup - HTML & XML parser

scikit-learn - machine learning library for python

nltk - natural language processessing

<code>import my_module</code> to import a library


In [1]:
import math

x = 2
y1 = math.exp(x)
y2 = math.log(x)

print("e^{} is {} and log({}) is {}".format(x, y1, x, y2))

e^2 is 7.38905609893065 and log(2) is 0.6931471805599453


In [2]:
import datetime

t = datetime.time(11, 21, 33)
print(t)
print('hour  :', t.hour)
print('minute:', t.minute)
print('second:', t.second)
print('microsecond:', t.microsecond)
print('tzinfo:', t.tzinfo)

11:21:33
hour  : 11
minute: 21
second: 33
microsecond: 0
tzinfo: None


In [3]:
today = datetime.datetime.today()
print(today)

tomorrow = today + datetime.timedelta(days=1)  
print(tomorrow)

2021-03-30 14:43:32.381382
2021-03-31 14:43:32.381382


In [6]:
today = datetime.datetime.today()
print('ISO     :', today)

str_format = "%a %b %d %H:%M:%S %Y"
s = today.strftime(str_format)
print('strftime:', s)

d = datetime.datetime.strptime(s, str_format)
print('strptime:', d.strftime(str_format))

s = "07/03/2017"

str_format = "%m/%d/%Y"

d = datetime.datetime.strptime(s, str_format)
print(d)


ISO     : 2021-03-30 14:44:44.877605
strftime: Tue Mar 30 14:44:44 2021
strptime: Tue Mar 30 14:44:44 2021
2017-07-03 00:00:00


In [1]:
import numpy as np

x = [1, 7, 3, 4, 0, -5]
y = np.array(x)
print(y)

print(np.array(range(5)))
print(np.arange(2,3,0.2))
print(np.linspace(2,3,5))
print(np.logspace(2,3,5))

print(np.zeros(5))
[print(" sample 5 :", np.ones((5,5,5), dtype=int))]

[ 1  7  3  4  0 -5]
[0 1 2 3 4]
[2.  2.2 2.4 2.6 2.8]
[2.   2.25 2.5  2.75 3.  ]
[ 100.          177.827941    316.22776602  562.34132519 1000.        ]
[0. 0. 0. 0. 0.]
 sample 5 : [[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


[None]